const colors = {
  MAIN_THEME_PURPLE: '#5651D4',
  MAIN_THEME_GRAY: '#A3A3A3',
  ACCENT_BUTTON_TEXT: '#FFFFFF',
  FLAT_LIST_BORDER: '#E1E1E1',
  FRIEND_NAME_TEXT: '#000000',
  SCREEN_TITLE: '#000000',
  REQUESTS_TITLE: '#333333',
  SEE_MORE: '#F8A53B',
  SEARCH_LINE_BACKGROUND: '#F5F5F5',
  FRIENDS_SCREEN_BACKGROUND: '#FFFFFF',
  EXIT_COLOR: '#F44E4E',
};

export default colors;
